import './globals.css'
import { Inter } from 'next/font/google'
import ClientSessionProvider from "@/components/session-provider"
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Geo Simulation System',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientSessionProvider>
          {children}
        </ClientSessionProvider>
      </body>
    </html>
  )
}
