import './globals.css'
import { Noto_Sans_SC, Noto_Serif_SC, Liu_Jian_Mao_Cao } from 'next/font/google'
import ClientSessionProvider from "@/components/session-provider"

const fontSans = Noto_Sans_SC({
  subsets:["latin"],
  weight:["100", "500", "900"],
  variable: "--font-sans",
})

const fontSerif = Noto_Serif_SC({
  subsets:["latin"],
  weight:["200", "500", "900"],
  variable: "--font_serif",
})

export const metadata = {
  title: 'App',
  description: 'Generated by create next app',
}

function Header() {
  return (
    <nav className="relative container mx-auto p-6 bg-gray-100 text-xl">
      地缘模拟系统
    </nav>
  )
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={fontSans.variable}>
        <ClientSessionProvider>
          <Header />
          {children}
        </ClientSessionProvider>
      </body>
    </html>
  )
}
