import './globals.css'
import { Inter } from 'next/font/google'
import ClientSessionProvider from "@/components/session-provider"
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'App',
  description: 'Generated by create next app',
}

function Header() {
  return (
    <nav className="relative container mx-auto p-6 bg-gray-100">
      Hello
    </nav>
  )
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientSessionProvider>
          <Header />
          {children}
        </ClientSessionProvider>
      </body>
    </html>
  )
}
